name: daily_running
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2


  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.4
  firebase_storage: ^8.1.0
  fluttertoast: ^8.0.7
  shared_preferences: ^2.0.6
  image_picker: ^0.7.5+3
  cached_network_image: ^3.0.0
  intl: ^0.17.0
  provider: ^5.0.0
  uuid: ^3.0.4
  flutter_spinkit: ^5.0.0
  flutter_launcher_icons: ^0.9.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^9.0.0
  numberpicker: ^2.1.1
  tab_indicator_styler: ^1.0.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: SpringBlueVinyl
      fonts:
        - asset: assets/fonts/font_spring_blue_vinyl.otf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
    - family: SVN Avo
      fonts:
        - asset: assets/fonts/svn_avo.ttf
        - asset: assets/fonts/svn_avo_bold.ttf
    - family: SVN Avo
      fonts:
        - asset: assets/fonts/LoginIcon.ttf

