/// Flutter icons RunningIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RunningIcons
///      fonts:
///       - asset: fonts/RunningIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class RunningIcons {
  RunningIcons._();

  static const _kFontFam = 'RunningIcons';
  static const String _kFontPkg = null;

  static const IconData profile =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_home =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
